# Generated by Django 4.2.3 on 2023-07-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle1', models.CharField(max_length=20)),
                ('pageDescription', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'tblabout',
            },
        ),
        migrations.CreateModel(
            name='contactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblcontactdetails',
            },
        ),
    ]
