# Generated by Django 4.2.3 on 2023-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=20)),
                ('servicedescription', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=20)),
                ('image', models.ImageField(default='bg23.jpg', upload_to='service_images')),
                ('creationdate', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblservices',
            },
        ),
    ]
