# Generated by Django 4.2.3 on 2023-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_service_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_detail',
            name='creationdate',
            field=models.DateTimeField(),
        ),
    ]
