# Generated by Django 4.2.3 on 2023-08-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0004_alter_service_detail_servicedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='staff',
            new_name='users',
        ),
    ]
