# Generated by Django 4.2.3 on 2023-08-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0005_rename_staff_customerprofile_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='users',
            new_name='staff',
        ),
    ]
