# Generated by Django 4.2.3 on 2023-08-04 07:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdashboard', '0006_rename_users_customerprofile_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptNumber', models.CharField(max_length=200)),
                ('aptDate', models.DateField(default=datetime.datetime.now)),
                ('aptTime', models.CharField(choices=[('8 AM', '8 AM'), ('10 AM', '10 AM'), ('12 AM', '12 AM'), ('2 PM', '2 PM'), ('4 PM', '4 PM')], default='2 PM', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblappointment',
            },
        ),
    ]
