# Generated by Django 4.2.3 on 2023-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0007_appointmentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbook',
            name='serviceDescription',
            field=models.CharField(choices=[('Maintenance and Tune-ups', 'Maintenance and Tune-ups'), ('Brake and Suspension', 'Brake and Suspension'), ('Diagnostic Services', 'Diagnostic Services'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
