# Generated by Django 4.2.3 on 2023-08-04 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdashboard', '0008_appointmentbook_servicedescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointmentBook',
            new_name='appointmentBooking',
        ),
    ]
