# Generated by Django 4.2.3 on 2023-08-04 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0012_alter_appointmentbooking_aptdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='aptDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
