# Generated by Django 4.2.3 on 2023-08-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0015_rename_user_appointmentbooking_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentBooking',
        ),
    ]
